name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Git
        run: |
          git config --global user.name 'arexdiaz'
          git config --global user.email 'arexito@icloud.com'

      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/runelite/runelite.git
          git fetch upstream
          git pull upstream master
          git push origin master
